In [15]:
file_1 = open("numbers.text", "r") 
print(file_1.read())
file_1.close()

3
45
83
213


In [ ]:
def mark_grade(percentage):
    print("Hello, welcome to our grade system, please follow the intructions:")
    name= input("Please Enter your name: ")
    percentage=int(input("Please Enter your percentage mark: "))
    if percentage <40 or percentage <= 49:
        print("Unfortunatly,", name +" ,you have not passed this module:" "grade: D")
    elif percentage > 50 and percentage <60:
        print(name +" ,you have have passed the module:" "grade: C")
    elif percentage >=60 and percentage <80:
        print(name+",you have passed the module:" "grade:B")
    elif percentage >=80 and percentage <= 100:
        print("Excellent", name+", you have succesfully passed the module:""grade: A")
    else:
        print("Error")
    return name

In [ ]:
x = mark_grade("name")
print(x)

In [11]:
import numpy as np
array= np.array([0, 1, 2, 3, 4, 5, 6,7,8,9])
print(array)


[0 1 2 3 4 5 6 7 8 9]


In [10]:
array =np.array([1,2,3,4,5,6,7,8,9])
new_array=array.reshape(3,3)
print(new_array)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [9]:
array=np.arange(0,12,2)
print(array)

[ 0  2  4  6  8 10]


In [ ]:
array=np.arange(1,12,)
print("substract:", array-1)

In [8]:
first_d= np.array ([(1,2,3,4),(5,6,7,8)])
print(first_d)

[[1 2 3 4]
 [5 6 7 8]]


In [14]:
a=np.array([6,7,10])
b=np.array([8,9,3])
c=np.dot(a,b)
sum=np.sum(c)
print(c)


141
